pipeline {
    agent any
    stages {
        stage('Setup virtual environment') {
            steps {
                dir('HW2') {
                    sh '''python3 -m venv env
                    source env/bin/activate
                    pip install -r requirements.txt'''
                }
            }
        }
        stage('Preprocessing data') {
            steps {
                dir('HW2/py_scripts') {
                    sh '''
                    python3 data_preprocessing.py
                    '''
                }
            }
        }
        stage('HW2/py_scripts') {
            steps {
                dir('HW2/py_scripts') {
                    sh '''
                    python3 model_preparation.py
                    '''
                }
            }
        }
        stage('Model testing') {
            steps {
                dir('HW2/py_scripts') {
                    sh '''
                    python3 model_testing.py
                    '''
                }
            }
        }
    }
    post {
        always {
            echo 'The pipeline is finished!'
        }
        success {
            echo 'The build was successful!'
        }
        failure {
            echo 'The build failed.'
        }
    }
}