services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: streamlit-iris-predict-image
    container_name: streamlit-iris-predict-container
    ports:
      - "8501:8501"
    volumes:
      - .:/app